
#include "SioAccess.h"

//
// The trace message header file must be included in a source file
// before any WPP macro calls and after defining a WPP_CONTROL_GUIDS
// macro. During the compilation, WPP scans the source files for
// TraceEvents() calls and builds a .tmh file which stores a unique
// data GUID for each message, the text resource string for each message,
// and the data types of the variables passed in for each message.
// This file is automatically generated and used during post-processing.
//
#include "SioAccess.tmh"

#ifdef ALLOC_PRAGMA
#pragma alloc_text( INIT, DriverEntry )
#pragma alloc_text( PAGE, SioAccDeviceAdd)
#pragma alloc_text( PAGE, SioAccEvtDriverContextCleanup)
#pragma alloc_text( PAGE, SioAccEvtDriverUnload)
#pragma alloc_text( PAGE, SioAccEvtDeviceFileCreate)
#pragma alloc_text( PAGE, SioAccEvtFileClose)
#pragma alloc_text( PAGE, SioAccEvtIoDeviceControl)
#endif // ALLOC_PRAGMA


NTSTATUS
DriverEntry(
    IN OUT PDRIVER_OBJECT   DriverObject,
    IN PUNICODE_STRING      RegistryPath
)
/*++

Routine Description:
    This routine is called by the Operating System to initialize the driver.

    It creates the device object, fills in the dispatch entry points and
    completes the initialization.

Arguments:
    DriverObject - a pointer to the object that represents this device
    driver.

    RegistryPath - a pointer to our Services key in the registry.

Return Value:
    STATUS_SUCCESS if initialized; an error otherwise.

--*/
{
    NTSTATUS                       status;
    WDF_DRIVER_CONFIG              config;
    WDFDRIVER                      hDriver;
    PWDFDEVICE_INIT                pInit = NULL;
    WDF_OBJECT_ATTRIBUTES          attributes;

    KdPrint(("Driver Frameworks SioAcc Legacy Driver Example\n"));


    WDF_DRIVER_CONFIG_INIT(
        &config,
        WDF_NO_EVENT_CALLBACK // This is a non-pnp driver.
    );

    //
    // Tell the framework that this is non-pnp driver so that it doesn't
    // set the default AddDevice routine.
    //
    config.DriverInitFlags |= WdfDriverInitNonPnpDriver;

    //
    // NonPnp driver must explicitly register an unload routine for
    // the driver to be unloaded.
    //
    config.EvtDriverUnload = SioAccEvtDriverUnload;

    //
    // Register a cleanup callback so that we can call WPP_CLEANUP when
    // the framework driver object is deleted during driver unload.
    //
    WDF_OBJECT_ATTRIBUTES_INIT(&attributes);
    attributes.EvtCleanupCallback = SioAccEvtDriverContextCleanup;

    //
    // Create a framework driver object to represent our driver.
    //
    status = WdfDriverCreate(DriverObject,
        RegistryPath,
        &attributes,
        &config,
        &hDriver);
    if (!NT_SUCCESS(status)) {
        KdPrint(("SioAcc: WdfDriverCreate failed with status 0x%x\n", status));
        return status;
    }

    //
    // Since we are calling WPP_CLEANUP in the DriverContextCleanup
    // callback we should initialize WPP Tracing after WDFDRIVER
    // object is created to ensure that we cleanup WPP properly
    // if we return failure status from DriverEntry. This
    // eliminates the need to call WPP_CLEANUP in every path
    // of DriverEntry.
    //
    WPP_INIT_TRACING(DriverObject, RegistryPath);

    //
    // On Win2K system,  you will experience some delay in getting trace events
    // due to the way the ETW is activated to accept trace messages.
    //
    KdPrint(("SioAcc: DriverEntry: tracing enabled\n"));

    TraceEvents(TRACE_LEVEL_VERBOSE, DBG_INIT,
        "Driver Frameworks SioAcc Legacy Driver Example");

    //
    //
    // In order to create a control device, we first need to allocate a
    // WDFDEVICE_INIT structure and set all properties.
    //
    pInit = WdfControlDeviceInitAllocate(
        hDriver,
        &SDDL_DEVOBJ_SYS_ALL_ADM_RWX_WORLD_RW_RES_R
    );

    if (pInit == NULL) {
        status = STATUS_INSUFFICIENT_RESOURCES;
        return status;
    }

    //
    // Call SioAccDeviceAdd to create a deviceobject to represent our
    // software device.
    //
    status = SioAccDeviceAdd(hDriver, pInit);

    return status;
}

NTSTATUS
SioAccDeviceAdd(
    IN WDFDRIVER Driver,
    IN PWDFDEVICE_INIT DeviceInit
)
/*++

Routine Description:

    Called by the DriverEntry to create a control-device. This call is
    responsible for freeing the memory for DeviceInit.

Arguments:

    DriverObject - a pointer to the object that represents this device
    driver.

    DeviceInit - Pointer to a driver-allocated WDFDEVICE_INIT structure.

Return Value:

    STATUS_SUCCESS if initialized; an error otherwise.

--*/
{
    NTSTATUS                       status;
    WDF_OBJECT_ATTRIBUTES           attributes;
    WDF_IO_QUEUE_CONFIG      ioQueueConfig;
    WDF_FILEOBJECT_CONFIG fileConfig;
    WDFQUEUE                            queue;
    WDFDEVICE   controlDevice;
    DECLARE_CONST_UNICODE_STRING(ntDeviceName, NTDEVICE_NAME_STRING);
    DECLARE_CONST_UNICODE_STRING(symbolicLinkName, SYMBOLIC_NAME_STRING);

    UNREFERENCED_PARAMETER(Driver);

    PAGED_CODE();

    TraceEvents(TRACE_LEVEL_VERBOSE, DBG_INIT,
        "SioAccDeviceAdd DeviceInit %p\n", DeviceInit);
    //
    // Set exclusive to TRUE so that no more than one app can talk to the
    // control device at any time.
    //
    WdfDeviceInitSetExclusive(DeviceInit, TRUE);

    WdfDeviceInitSetIoType(DeviceInit, WdfDeviceIoBuffered);


    status = WdfDeviceInitAssignName(DeviceInit, &ntDeviceName);

    if (!NT_SUCCESS(status)) {
        TraceEvents(TRACE_LEVEL_ERROR, DBG_INIT, "WdfDeviceInitAssignName failed %!STATUS!", status);
        goto End;
    }

    WdfControlDeviceInitSetShutdownNotification(DeviceInit,
        SioAccShutdown,
        WdfDeviceShutdown);

    //
    // Initialize WDF_FILEOBJECT_CONFIG_INIT struct to tell the
    // framework whether you are interested in handling Create, Close and
    // Cleanup requests that gets generated when an application or another
    // kernel component opens an handle to the device. If you don't register
    // the framework default behaviour would be to complete these requests
    // with STATUS_SUCCESS. A driver might be interested in registering these
    // events if it wants to do security validation and also wants to maintain
    // per handle (fileobject) context.
    //

    WDF_FILEOBJECT_CONFIG_INIT(
        &fileConfig,
        SioAccEvtDeviceFileCreate,
        SioAccEvtFileClose,
        WDF_NO_EVENT_CALLBACK // not interested in Cleanup
    );

    WdfDeviceInitSetFileObjectConfig(DeviceInit,
        &fileConfig,
        WDF_NO_OBJECT_ATTRIBUTES);

    //
    // Specify the size of device context
    //
    WDF_OBJECT_ATTRIBUTES_INIT_CONTEXT_TYPE(&attributes,
        CONTROL_DEVICE_EXTENSION);

    status = WdfDeviceCreate(&DeviceInit,
        &attributes,
        &controlDevice);
    if (!NT_SUCCESS(status)) {
        TraceEvents(TRACE_LEVEL_ERROR, DBG_INIT, "WdfDeviceCreate failed %!STATUS!", status);
        goto End;
    }

    //
    // Create a symbolic link for the control object so that usermode can open
    // the device.
    //

    status = WdfDeviceCreateSymbolicLink(controlDevice,
        &symbolicLinkName);

    if (!NT_SUCCESS(status)) {
        //
        // Control device will be deleted automatically by the framework.
        //
        TraceEvents(TRACE_LEVEL_ERROR, DBG_INIT, "WdfDeviceCreateSymbolicLink failed %!STATUS!", status);
        goto End;
    }

    //
    // Configure a default queue so that requests that are not
    // configure-fowarded using WdfDeviceConfigureRequestDispatching to goto
    // other queues get dispatched here.
    //
    WDF_IO_QUEUE_CONFIG_INIT_DEFAULT_QUEUE(&ioQueueConfig,
        WdfIoQueueDispatchSequential);

    // ioQueueConfig.EvtIoRead = SioAccEvtIoRead;
    // ioQueueConfig.EvtIoWrite = SioAccEvtIoWrite;
    ioQueueConfig.EvtIoDeviceControl = SioAccEvtIoDeviceControl;

    WDF_OBJECT_ATTRIBUTES_INIT(&attributes);
    //
    // Since we are using Zw function set execution level to passive so that
    // framework ensures that our Io callbacks called at only passive-level
    // even if the request came in at DISPATCH_LEVEL from another driver.
    //
    //attributes.ExecutionLevel = WdfExecutionLevelPassive;

    //
    // By default, Static Driver Verifier (SDV) displays a warning if it 
    // doesn't find the EvtIoStop callback on a power-managed queue. 
    // The 'assume' below causes SDV to suppress this warning. If the driver 
    // has not explicitly set PowerManaged to WdfFalse, the framework creates
    // power-managed queues when the device is not a filter driver.  Normally 
    // the EvtIoStop is required for power-managed queues, but for this driver
    // it is not needed b/c the driver doesn't hold on to the requests or 
    // forward them to other drivers. This driver completes the requests 
    // directly in the queue's handlers. If the EvtIoStop callback is not 
    // implemented, the framework waits for all driver-owned requests to be
    // done before moving in the Dx/sleep states or before removing the 
    // device, which is the correct behavior for this type of driver.
    // If the requests were taking an indeterminate amount of time to complete,
    // or if the driver forwarded the requests to a lower driver/another stack,
    // the queue should have an EvtIoStop/EvtIoResume.
    //
    __analysis_assume(ioQueueConfig.EvtIoStop != 0);
    status = WdfIoQueueCreate(controlDevice,
        &ioQueueConfig,
        &attributes,
        &queue // pointer to default queue
    );
    __analysis_assume(ioQueueConfig.EvtIoStop == 0);
    if (!NT_SUCCESS(status)) {
        TraceEvents(TRACE_LEVEL_ERROR, DBG_INIT, "WdfIoQueueCreate failed %!STATUS!", status);
        goto End;
    }

    //
    // Control devices must notify WDF when they are done initializing.   I/O is
    // rejected until this call is made.
    //
    WdfControlFinishInitializing(controlDevice);

End:
    //
    // If the device is created successfully, framework would clear the
    // DeviceInit value. Otherwise device create must have failed so we
    // should free the memory ourself.
    //
    if (DeviceInit != NULL) {
        WdfDeviceInitFree(DeviceInit);
    }

    return status;

}

VOID
SioAccEvtDriverContextCleanup(
    IN WDFOBJECT Driver
)
/*++
Routine Description:

   Called when the driver object is deleted during driver unload.
   You can free all the resources created in DriverEntry that are
   not automatically freed by the framework.

Arguments:

    Driver - Handle to a framework driver object created in DriverEntry

Return Value:

    NTSTATUS

--*/
{
    TraceEvents(TRACE_LEVEL_VERBOSE, DBG_INIT,
        "Entered SioAccEvtDriverContextCleanup\n");

    PAGED_CODE();

    //
    // No need to free the controldevice object explicitly because it will
    // be deleted when the Driver object is deleted due to the default parent
    // child relationship between Driver and ControlDevice.
    //
    WPP_CLEANUP(WdfDriverWdmGetDriverObject((WDFDRIVER)Driver));

}


VOID
SioAccEvtDeviceFileCreate(
    IN WDFDEVICE            Device,
    IN WDFREQUEST Request,
    IN WDFFILEOBJECT        FileObject
)
/*++

Routine Description:

    The framework calls a driver's EvtDeviceFileCreate callback
    when it receives an IRP_MJ_CREATE request.
    The system sends this request when a user application opens the
    device to perform an I/O operation, such as reading or writing a file.
    This callback is called synchronously, in the context of the thread
    that created the IRP_MJ_CREATE request.

Arguments:

    Device - Handle to a framework device object.
    FileObject - Pointer to fileobject that represents the open handle.
    CreateParams - Parameters of IO_STACK_LOCATION for create

Return Value:

   NT status code

--*/
{
    NTSTATUS                    status = STATUS_SUCCESS;

    UNREFERENCED_PARAMETER(Device);
    UNREFERENCED_PARAMETER(FileObject);

    PAGED_CODE();

    WdfRequestComplete(Request, status);

    return;
}


VOID
SioAccEvtFileClose(
    IN WDFFILEOBJECT    FileObject
)

/*++

Routine Description:

   EvtFileClose is called when all the handles represented by the FileObject
   is closed and all the references to FileObject is removed. This callback
   may get called in an arbitrary thread context instead of the thread that
   called CloseHandle. If you want to delete any per FileObject context that
   must be done in the context of the user thread that made the Create call,
   you should do that in the EvtDeviceCleanp callback.

Arguments:

    FileObject - Pointer to fileobject that represents the open handle.

Return Value:

   VOID

--*/
{
    UNREFERENCED_PARAMETER(FileObject);

    PAGED_CODE();

    TraceEvents(TRACE_LEVEL_VERBOSE, DBG_INIT, "SioAccEvtFileClose\n");

    return;
}

VOID
SioAccEvtIoDeviceControl(
    IN WDFQUEUE         Queue,
    IN WDFREQUEST       Request,
    IN size_t            OutputBufferLength,
    IN size_t            InputBufferLength,
    IN ULONG            IoControlCode
)
/*++
Routine Description:

    This event is called when the framework receives IRP_MJ_DEVICE_CONTROL
    requests from the system.

Arguments:

    Queue - Handle to the framework queue object that is associated
            with the I/O request.
    Request - Handle to a framework request object.

    OutputBufferLength - length of the request's output buffer,
                        if an output buffer is available.
    InputBufferLength - length of the request's input buffer,
                        if an input buffer is available.

    IoControlCode - the driver-defined or system-defined I/O control code
                    (IOCTL) that is associated with the request.

Return Value:

   VOID

--*/
{
    NTSTATUS            status = STATUS_SUCCESS;// Assume success

    UNREFERENCED_PARAMETER(Queue);

    PAGED_CODE();

    if (!OutputBufferLength || !InputBufferLength)
    {
        WdfRequestComplete(Request, STATUS_INVALID_PARAMETER);
        return;
    }

    //
    // Determine which I/O control code was specified.
    //

    switch (IoControlCode)
    {
    case IOCTL_CUSTOM_READ_IO_COMMAND:
        KdPrint(("IOCTL_CUSTOM_READ_IO_COMMAND\n"));
        status = ReadIoPort(Request, IoControlCode);
        break;

    case IOCTL_CUSTOM_WRITE_IO_COMMAND:
        KdPrint(("IOCTL_CUSTOM_WRITE_IO_COMMAND\n"));
        status = WriteIoPort(Request, IoControlCode);
        break;

    default:

        //
        // The specified I/O control code is unrecognized by this driver.
        //
        status = STATUS_INVALID_DEVICE_REQUEST;
        TraceEvents(TRACE_LEVEL_ERROR, DBG_IOCTL, "ERROR: unrecognized IOCTL %x\n", IoControlCode);
        break;
    }

    TraceEvents(TRACE_LEVEL_VERBOSE, DBG_IOCTL, "Completing Request %p with status %X",
        Request, status);

    WdfRequestComplete(Request, status);

}

VOID
SioAccShutdown(
    WDFDEVICE Device
)
/*++

Routine Description:
    Callback invoked when the machine is shutting down.  If you register for
    a last chance shutdown notification you cannot do the following:
    o Call any pageable routines
    o Access pageable memory
    o Perform any file I/O operations

    If you register for a normal shutdown notification, all of these are
    available to you.

    This function implementation does nothing, but if you had any outstanding
    file handles open, this is where you would close them.

Arguments:
    Device - The device which registered the notification during init

Return Value:
    None

  --*/

{
    UNREFERENCED_PARAMETER(Device);
    return;
}


VOID
SioAccEvtDriverUnload(
    IN WDFDRIVER Driver
)
/*++
Routine Description:

   Called by the I/O subsystem just before unloading the driver.
   You can free the resources created in the DriverEntry either
   in this routine or in the EvtDriverContextCleanup callback.

Arguments:

    Driver - Handle to a framework driver object created in DriverEntry

Return Value:

    NTSTATUS

--*/
{
    UNREFERENCED_PARAMETER(Driver);

    PAGED_CODE();

    TraceEvents(TRACE_LEVEL_VERBOSE, DBG_INIT, "Entered SioAccDriverUnload\n");

    return;
}

NTSTATUS
ReadIoPort(
    IN WDFREQUEST Request,
    IN ULONG IoControlCode
)
{
    NTSTATUS Status;
    UCHAR Data;
    USHORT PortNumber;
    PIO_PORT_INPUT InputData = NULL;
    size_t InDataSize;
    PVOID outBuf = NULL;
    size_t outBufSize = 0;

    UNREFERENCED_PARAMETER(IoControlCode);

    Status = WdfRequestRetrieveInputBuffer(Request, sizeof(IO_PORT_INPUT), (PVOID*)&InputData, &InDataSize);
    if (!NT_SUCCESS(Status)) {
        return STATUS_INSUFFICIENT_RESOURCES;
    }

    Status = WdfRequestRetrieveOutputBuffer(Request, 0, &outBuf, &outBufSize);
    if (!NT_SUCCESS(Status)) {
        return STATUS_INSUFFICIENT_RESOURCES;
    }

    if ((outBuf == NULL) || (outBufSize == 0)) {
        return STATUS_BUFFER_TOO_SMALL;
    }

    PortNumber = (USHORT)InputData->PortNumber;
    KdPrint(("PortNumber %x\n", PortNumber));
    if ((PortNumber != SIO_INDEX_PORT) && (PortNumber != SIO_DATA_PORT) &&
        (PortNumber != SEC_SIO_INDEX_PORT) && (PortNumber != SEC_SIO_DATA_PORT) &&
        (PortNumber != (SIO_HWM_PORT_0 + 0x05)) && (PortNumber != (SIO_HWM_PORT_0 + 0x06)) &&
        (PortNumber != (SIO_HWM_PORT_1 + 0x05)) && (PortNumber != (SIO_HWM_PORT_1 + 0x06)))
    {
        return STATUS_INVALID_PARAMETER;
    }

    Data = READ_PORT_UCHAR((PUCHAR)(ULONG_PTR)InputData->PortNumber);
    KdPrint(("Data %x\n", Data));
    RtlCopyMemory(outBuf, &Data, sizeof(UCHAR));

    WdfRequestSetInformation(Request, sizeof(UCHAR));

    return STATUS_SUCCESS;
}

NTSTATUS
WriteIoPort(
    IN WDFREQUEST Request,
    IN ULONG IoControlCode
)
{
    NTSTATUS Status;
    USHORT PortNumber;
    PIO_PORT_INPUT InputData = NULL;
    size_t InDataSize;

    UNREFERENCED_PARAMETER(IoControlCode);

    Status = WdfRequestRetrieveInputBuffer(Request, sizeof(IO_PORT_INPUT), (PVOID*)&InputData, &InDataSize);
    if (!NT_SUCCESS(Status)) {
        return STATUS_INSUFFICIENT_RESOURCES;
    }

    PortNumber = (USHORT)InputData->PortNumber;
    KdPrint(("PortNumber %x, WriteData %x\n", PortNumber, InputData->IoPortData.CharData));
    if ((PortNumber != SIO_INDEX_PORT) && (PortNumber != SIO_DATA_PORT) &&
        (PortNumber != SEC_SIO_INDEX_PORT) && (PortNumber != SEC_SIO_DATA_PORT) &&
        (PortNumber != (SIO_HWM_PORT_0 + 0x05)) && (PortNumber != (SIO_HWM_PORT_0 + 0x06)) &&
        (PortNumber != (SIO_HWM_PORT_1 + 0x05)) && (PortNumber != (SIO_HWM_PORT_1 + 0x06)))
    {
        return STATUS_INVALID_PARAMETER;
    }

    WRITE_PORT_UCHAR((PUCHAR)(ULONG_PTR)InputData->PortNumber, InputData->IoPortData.CharData);

    return STATUS_SUCCESS;
}